title: BotanyBase
baseurl: botanybase.github.io

pagination: 10
paginate_path: "/page/:num"

plugins: 
 - jekyll-paginate
 - jekyll-sitemap
 - jekyll-language-plugin

language_data: data.lang.%%
language_includes_dir: _i18n
