name: Update Plants JSON
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      image:
        type: string
      climate:
        type: string
      description:
        type: string
jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Update JSON
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          fetch('https://api.github.com/repos/BotanyBase/botanybase.github.io/contents/identify/plants.json', {
            method: 'PUT',
            headers: {
              'Content-Type': 'application/json',
              Authorization: 'Bearer $GITHUB_TOKEN'
            },
            body: JSON.stringify({
              name: '${name}',
              image: '${image}',
              climate: '${climate}',
              description: '${description}'
            })
          })
