name: Add Plant

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Plant Name'
        required: true
      image:
        description: 'Plant Image URL'
        required: true
      climate:
        description: 'Plant Climate'
        required: true
      description:
        description: 'Plant Description'
        required: true

jobs:
  update-plants:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch plants.json
        uses: actions/github-script@v6
        with:
          script: |
            const plantsJson = JSON.parse(fs.readFileSync('plants.json', 'utf8'));
            const newPlant = {
              name: github.context.inputs.name,
              image: github.context.inputs.image,
              climate: github.context.inputs.climate,
              description: github.context.inputs.description
            };
            plantsJson.push(newPlant);
            fs.writeFileSync('plants.json', JSON.stringify(plantsJson, null, 2));
      - name: Commit and push changes
        uses: actions/github-script@v6
        with:
          script: |
            git add .
            git commit -m "Add new plant: ${github.context.inputs.name}"
            git push origin main
