name: Update Plants JSON

on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      image:
        type: string
      climate:
        type: string
      description:
        type: string

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Update JSON
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          curl -X PUT \
          https://api.github.com/repos/BotanyBase/botanybase.github.io/contents/identify/plants.json \
          -H 'Content-Type: application/json' \
          -H 'Authorization: Bearer $GITHUB_TOKEN' \
          -d '{"name": "${name}", "image": "${image}", "climate": "${climate}", "description": "${description}"}'
          
