# .github/workflows/add-plant.yml

name: Add Plant to Database

on:
  repository_dispatch:
    workflows: add-plant

jobs:
  add-plant:
    runs-on: ubuntu-latest
    steps:
      - uses: github-forms/validate@v1
        with:
          schema: |
            {
              "type": "object",
              "properties": {
                "name": {"type": "string"},
                "image": {"type": "string"},
                "climate": {"enum": ["tropical", "subtropical", "temperate", "alpine", "desert"]},
                "description": {"type": "string"}
              },
              "required": ["name", "image", "climate", "description"]
            }
      - uses: github-api/update-file@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          file-path: 'identify/plants.json'
          json-data: |
            {
              "name": "${{ github.forms.name }}",
              "image": "${{ github.forms.image }}",
              "climate": "${{ github.forms.climate }}",
              "description": "${{ github.forms.description }}"
            }
      - name: Commit changes
        uses: github-actions/commit@v4
        with:
          message: 'Add new plant entry'
