name: Create Issue from HTML Form

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
      image:
        description: 'Image'
        required: true
      climate:
        description: 'Climate'
        required: true
      description:
        description: 'Description'
        required: true

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create issue from form inputs
        uses: github-actions/github-script@v5
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            github.issues.create({
              owner: github.repository_owner,
              repo: github.repository_name,
              title: "${ inputs.name }",
              body: "Image: ${ inputs.image }\nClimate: ${ inputs.climate }\nDescription: ${ inputs.description }"
            })
