name: Create Issue

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name'
        required: true
      image:
        description: 'Image'
        required: true
      climate:
        description: 'Climate'
        required: true
      description:
        description: 'Description'
        required: true

jobs:
  add-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add Issue
        run: |
          echo "Adding issue to repository..."
          GITHUB_EVENT_TITLE="${name}"
          GITHUB_EVENT_BODY="${description}"
          cat (link unavailable) | sed -e "s/{{title}}/${GITHUB_EVENT_TITLE}/" | sed -e "s/{{body}}/${GITHUB_EVENT_BODY}/" | gh issue create
      - uses: github/gh-actions-issues@v1
