name: Plant Submission Workflow
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      image:
        type: string
      climate:
        type: string
      description:
        type: string
jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Issue
        uses: actions/create-issue@v2
        with:
          title: ${{ github.actions.inputs.name }}
          body: |
            Image: ${{ github.actions.inputs.image }}
            Climate: ${{ github.actions.inputs.climate }}
            Description: ${{ github.actions.inputs.description }}

