name: Create GitHub Issue

on:
  # Define the event that triggers the workflow
  dispatch:
    types: [create-issue]  # This matches the event type you'll send from your HTML form handler

jobs:
  add-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'  # Use the latest Go version

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Verify GitHub CLI version
        run: gh --version

      - name: Create Issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TITLE: ${{ github.event.client_payload.title }}
          BODY: ${{ github.event.client_payload.body }}
        run: |
          echo "Adding issue to repository..."
          gh issue create --title "$TITLE" --body "$BODY"
